# -*- coding: utf-8 -*-
"""Inscription.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_PA3z2FxOylbTzbw3vZH6Q0aXR5uZOPe
"""

word = """

 d88888888888b  d8b     888  d88888888D        d8b         d8b    .d8888b.    .d88888b.
      888       888     888  888               888         888  .d8V    V8b.  888    d8b
      888       888     888  888               888   88    888  888      888  888    d88
      888       88888888888  888888D           888  8888   888  888 o88o 888  888oooV88
      888       888     888  888               88b d88 88b d88  888      888  888    V88
     .Y8D.      O8D     O8D  Y88888888D        .Y888P' 'P888Y.  U8Y      Y8U  D8Y     V8D

"""

print(word)